### ISSUE TITLE
Add custom header image support

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#1]

**Comment by schrapel** [comment]
Support from #1, #2, #3 can be removed from the child theme and placed in the parent theme once it's complete

**Comment by tobeycodes** [comment]
@chriswallace This probably needs design input 

Related functions but also can see how it works in the lyrical and ascension theme as they work quite differently but the parent theme powers it all but we need to also output on the parent theme.

https://developer.wordpress.org/reference/functions/get_custom_header/
https://developer.wordpress.org/reference/functions/get_header_image/
https://developer.wordpress.org/reference/functions/header_image/
