### ISSUE TITLE
Set hero overlay color automatically based on image

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#107]
We could use the [Grade.js](http://benhowdle.im/grade/) library to detect the dominant color in the user's selected header image, and use that as the overlay color.

This would allow us to move this control to the **Header Image** panel:

<img width="298" alt="screen shot 2016-09-10 at 9 15 14 am" src="https://cloud.githubusercontent.com/assets/522158/18411135/1e10ebae-7737-11e6-98e8-242185063a88.png">

I'm not sure how this will play out with Color Schemes. Like if you had selected the Plum scheme, and selected an image with a lot of bright red or something. We would have to test this a lot to gauge whether color clash would be a common occurrence.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
