### ISSUE TITLE
Changes to navigation

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#12]
There are a few issues with the navigation
1. It uses min-width and max-width. Ideally it should only use one and since the rest of the site is mobile first lets only use min-width. If we need to both, then it should be limited to only structural changes (floats, displays) but these things can still be achieved with only min-width
2. The javascript on the mobile menu does not work

**Comment by tobeycodes** [comment]
Now I made it so the site-title isn't forced to take up the entire header. We should strip back the navigation too. We could then more easily move the navigation from below the header region to inside it. 

https://github.com/godaddy/wp-primer-theme/commit/39e0b54f79614252c8cc3cc48add395f188b23d2

**Comment by tobeycodes** [comment]
I've just pushed up a rewrite of the navigation (https://github.com/godaddy/wp-primer-theme/commit/596859fed545c46c2c2054976e8560d35cbc189f)
1. The `menu-toggle` can now be outside of the `site-navigation` container
2. Show grand children on mobile with additional padding (hidden before)
3. Only mobile first with a breakpoint at 600px (as before)
4. The menu is no longer forced to take up the entire container, so easy to use multiple menus

If we want to introduce clickable dropdowns for children on mobile we will need to add a `<span>` in each element with the arrow since you before/after is not part of the DOM. 

Pretty happy about this part, it was bugging me before how hard the SCSS was to change.

@fjarrett @chriswallace please review

**Comment by frankiejarrett** [comment]
I'm happy with this.
