### ISSUE TITLE
Unable to Edit Header with Ease

### ISSUE THREAD

**Issue by Dman89** [godaddy/wp-primer-theme#126]
The text above the menu bar is not editable. If it is, it is unclear to my user how to edit it with ease.

**Comment by EvanHerman** [comment]
Hi @Dman89 ,

The text above the menu bar is contained inside of a text widget, in the 'Hero' widgetized area. You can access it from the customizer, by heading into 'Widgets > Hero' or from within dashboard.

Here is a screenshot to help illustrate that section:
![Customizer Hero](https://cldup.com/W-mX5sJ2Sn.png)

We are actively working on making it more intuitive on how to edit that section of the site.

Thanks,
Evan

**Comment by Dman89** [comment]
@EvanHerman
You truly are my "Hero"!
Thank you for the fast reply, I got it to work.

**Comment by EvanHerman** [comment]
@Dman89 Awesome! I'm glad I was able to help out. In future, things should be a little bit more intuitive for the end user.

Thanks again!
Evan

**Comment by Dman89** [comment]
Is there a way to keep the main header on all pages?

**Comment by Dman89** [comment]
@EvanHerman Is there a way to keep the main header on all pages?

**Comment by EvanHerman** [comment]
@Dman89 Give the following snippet a shot:

``` php
/**
 * Ensure the hero widget persists across all pages
 *
 * @author GoDaddy
 *
 * @return mixed  Hero widget markup.
 */
function godaddy_persistent_hero() {

    if ( ! is_front_page() && is_active_sidebar( 'hero' ) ) {

        dynamic_sidebar( 'hero' );

    }

}
add_action( 'primer_hero', 'godaddy_persistent_hero' );
```

You'll want to add the code to your themes `functions.php` file for it to start working. If you are not comfortable editing the themes `functions.php` file you can always use a third party plugin to enter custom snippets. One that works well is [My Custom Functions](https://wordpress.org/plugins/my-custom-functions/).

Let us know how that goes!

Evan
