### ISSUE TITLE
Use core paging function instead of custom ones

### ISSUE THREAD

**Issue by jonathanbardo** [godaddy/wp-primer-theme#127]
We should use core pagination function instead of the custom ones we took from the twenty series.

We need to replace `primer_post_nav` and `primer_paging_nav`

Ref: https://codex.wordpress.org/Function_Reference/posts_nav_link

**Comment by WPDevHQ** [comment]
The functions to use there are `the_post_navigation()` and `the_posts_pagination()` respectively.

This can be seen in the upcoming TwentySeventeen [single.php](https://github.com/WordPress/twentyseventeen/blob/master/single.php#L29) and [index.php](https://github.com/WordPress/twentyseventeen/blob/master/index.php#L46)

You can still call them via a custom function callback for easier hooking in to do_action() hooks as I do [here](https://github.com/WPDevHQ/actions/blob/master/inc/structure/post.php#L76).

**Comment by frankiejarrett** [comment]
@EvanHerman We missed the part about using `the_posts_pagination()` for `primer_paging_nav()`. Reopening.
