### ISSUE TITLE
Don't hardcode IE polyfills in header.php

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#13]
As discussed in https://github.com/godaddy/wp-primer-theme/issues/9 we will need to at least add https://github.com/keithclark/selectivizr and most likely some other changes to support older browsers

**Comment by tobeycodes** [comment]
We should enqueue any IE conditional stuff with instead of directly in header.php

https://developer.wordpress.org/reference/functions/wp_script_add_data/

**Comment by frankiejarrett** [comment]
Agreed. It's now a requirement on dot org: https://make.wordpress.org/themes/2016/07/26/meeting-notes-for-2016-july-26/

**Comment by jonathanbardo** [comment]
This is now resolve since we merged the susy branch.
