### ISSUE TITLE
How to fix author missing and updated missing on Search Console Report?

### ISSUE THREAD

**Issue by Frank0302** [godaddy/wp-primer-theme#132]
Help me, please.
My Google Search Console Report is like this:
[http://i1282.photobucket.com/albums/a536/Hatha_Yogi/Error_zpsjbxwr1xc.jpg](http://i1282.photobucket.com/albums/a536/Hatha_Yogi/Error_zpsjbxwr1xc.jpg)
I search this error on Google but I can't find the correct solution. It looks like the Primer theme is coded in unfamiliar way.
Thank you.

**Comment by frankiejarrett** [comment]
Duplicate of #133
