### ISSUE TITLE
Support video headers in WordPress 4.7

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#136]
We need to verify whether Primer will support video headers out-of-the-box when 4.7 lands, or if there is something we need to do to opt-in to the feature.

See https://make.wordpress.org/core/2016/11/26/video-headers-in-4-7/

**Comment by EvanHerman** [comment]
@fjarrett It looks like we'll have to refactor the header template to incorporate `the_custom_header_markup()` and build in a few new styles to accommodate video headers.

**Comment by caseymarte** [comment]
I updated Primer to wp 4,7 and I don't see the option in customize for video?

**Comment by weavertheme** [comment]
It won't show unless the theme supports header video.

**Comment by EvanHerman** [comment]
Hi @caseymarte ,

We are currently working on getting this feature built into primer. While we can easily add theme support for video headers, we need to adjust a few HTML elements and tweak a few styles so the video headers fit in to the theme properly.

Thanks for chiming in @weavertheme

**Comment by javadth** [comment]
using this theme in my website

[مداربسته دوربین](https://xn----zmcbckzcnev7qkavc6a.com/)
