### ISSUE TITLE
Pages numbered

### ISSUE THREAD

**Issue by glados1337** [godaddy/wp-primer-theme#137]
Hi,

How can i enable numbered pages? I have only Older Post, Thanks ;)

**Comment by glados1337** [comment]
Next one thing, how to remove arrow in the button? Thanks.

**Comment by glados1337** [comment]
Looks like no support :(

**Comment by EvanHerman** [comment]
Hi @glados1337,

Where are you looking to add numbered pages? Pagination is something that can be built out in your theme. We don't have an option to toggle on/off pagination.

https://codex.wordpress.org/Pagination

To respond to your second question, can you please provide us with a screenshot of what arrow you are referring to? I'm not sure I know what arrow within primer you are referencing.

Thanks,
Evan

**Comment by frankiejarrett** [comment]
Closing for now. Will reopen if more info is provided.
