### ISSUE TITLE
Page Header - Page title

### ISSUE THREAD

**Issue by LouNat** [godaddy/wp-primer-theme#138]
Hi !
Congratulations for your great Primer theme  :-)
I'm struggling with very basic issue (I'm a newbee with Worpress):
How can I modify the vertical size (height) of the page title header ?
I tried some CSS modifications but without any success.
Many many thanks for help !
Nat

**Comment by joshterrill** [comment]
Are you talking about the header that has the white band behind it? It does not have a set height, but it can be artificially modified by changing the font size of the h1 tag inside of it.

**Comment by EvanHerman** [comment]
Hi @LouNat,

You can modify the height of the header using CSS. As @joshterrill outlined, the container doesn't have a set height but is adjusted by the contents, padding and margin of the header.

What have tried? Providing us with some code that you have tried will help us provide a quicker and better solution.

Thanks,
Evan

**Comment by LouNat** [comment]
Dear,
Many thanks for your comments and suggestions, and sorry to react so lately.
The file Style.css shows this:

> .page-title-container {
>   background-color: #ffffff; }
>   .page-title-container .page-header {
>     max-width: 1100px;
>     margin-left: auto;
>     margin-right: auto;
>     position: relative;
>     clear: both; }
>     .page-title-container .page-header:after {
>       content: " ";
>       display: block;
>       clear: both; }
>     .page-title-container .page-header h1 {
>       width: 97.22222%;
>       float: left;
>       margin-left: 1.38889%;
>       margin-right: 1.38889%;
>       padding: 3% 1rem;
>       margin-bottom: 0;
>       font-weight: 300; }

No 'Height' actually.
I tried to modify the padding and the font-weight but these modifications had no effect.
Should I modify code elsewhere ?

Again, thank you for your help !
Nathalie

**Comment by EvanHerman** [comment]
Hi Nathalie,

Yes. You shouldn't be editing the core files. Anytime you update the plugin all of your changes are going to be lost.

Please add your changes into an MU plugin, use the Custom CSS section of the customizer, or install a third-party plugin that allows you to add custom CSS to your site.

The padding is the cause of the container height. There is no set height.


```css
.site-title-wrapper {
   padding: 3% 1rem;
}
```


Thanks,
Evan

**Comment by LouNat** [comment]
Thanks Evan !

I finally created a child theme.

Best,
Nathalie
