### ISSUE TITLE
Where would I find the content of <?php wp_head(); ?>

### ISSUE THREAD

**Issue by samonja** [godaddy/wp-primer-theme#141]
Where would I find the content of <?php wp_head(); ?>, I want to control the meta for the keywords of the  site.

**Comment by EvanHerman** [comment]
Hi @samonja,

The contents of `wp_head()` are a collection of actions built into WordPress. In other words, you can't access the contents of `wp_head()` directly.

What keywords are you trying to control? You can use a third party plugin to adjust some of the meta tags for your site, such as [Yoast SEO](https://wordpress.org/plugins/wordpress-seo/).

Evan

**Comment by frankiejarrett** [comment]
This should be handled by a plugin.

If this is about SEO, it's worth noting that Google stopped recognizing meta tags this as part of their ranking algorithm more than 7 years ago.

https://webmasters.googleblog.com/2009/09/google-does-not-use-keywords-meta-tag.html
