### ISSUE TITLE
Css for header button!

### ISSUE THREAD

**Issue by aseemghadiali** [godaddy/wp-primer-theme#142]
There was a default css for a "call to action" button in the header area which I deleted by mistake. Could anyone provide me that css please ?

**Comment by EvanHerman** [comment]
Hi @aseemghadiali,

The original markup for the call to action widget in the header is as follows:

```html
Grab your visitors' attention front and center on your homepage, then give them an action to take.

<a href="/contact/" class="button">Get Started</a>
```

Let us know if that helps out, or if you were looking for another set of markup.


Thanks,
Evan
