### ISSUE TITLE
Use specific (Layout) with bbpress

### ISSUE THREAD

**Issue by ELMANARA** [godaddy/wp-primer-theme#144]
Greetings,

Thank you for this great theme, I just have one question about using a specific layout for bbpress, I tried all the guides on bbpress forums but with no success, I hope I can find an answer here.

Thanks again for your time and effort.

Best Regards.

**Comment by EvanHerman** [comment]
Hi @ELMANARA ,

What sort of question do you have? I'd be glad to help out where I can.

Thanks,
Evan

**Comment by ELMANARA** [comment]
Thank you for the quick response.

All pages on my WordPress site use the "Two columns: Content and Sidebar" Layout, my bbpress forum doesn't fit well in this layout thus I need to use the "One Column: Wide" Layout for it.

BBpress forum mentions that you need to make a bbpress.php file with the layout required but I am clueless where to start.

https://bbpress.org/forums/topic/how-do-i-get-bbpress-pages-to-use-a-specific-page-template-in-wordpress/

**Comment by EvanHerman** [comment]
Hi @ELMANARA ,

Are you displaying the forums using a shortcode entered onto a page?

If so, Primer has some built in options to adjust the layout of the page right on the new/edit page in the dashboard.

**Example:**
![Example](https://cldup.com/unSHaG9Dqa.png)

If you see in the bottom right-hand corner of the screenshot you should be able to set the container layout to full width. This should avoid the need for creating an additional template file in your theme.

Let us know if that helps out.


Evan

**Comment by ELMANARA** [comment]
I created the link using a custom link through the Appearance customizer.

This is the link for the forum: http://www.monaelloboudy.com/forums/ (it is a Non-English website)

The attached example image is not showing.

**Comment by EvanHerman** [comment]
@ELMANARA 

Are you not able to edit that page via the dashboard?

Evan

**Comment by EvanHerman** [comment]
If you go into the specific Forum you are trying to edit from within the dashboard by clicking on the **Forums** link in the dashboard you should be able to alter the page template that is being used for the bbpress forum.

Here is an example screenshot to illustrate what I am talking about:

![Example](https://cldup.com/OTB5zGSY-2.png)

You can change the page layout on the bottom right-hand side of the page, inside of the 'Layout' container.


Evan

**Comment by ELMANARA** [comment]
@EvanHerman Thanks for this tip, now all the forums can be set to wide layout, but the main page for all forums can't be set to the wide layout, I have no access to this page through the dashboard it is just a custom link.

**Comment by EvanHerman** [comment]
Hi @ELMANARA ,

I think that's due to the way that bbpress generates that page. I think what you're going to have to do is create a custom bbpress template. Have you taken a look at the bbpress documentation on creating a custom template?
https://codex.bbpress.org/themes/theme-compatibility/getting-started-in-modifying-the-main-bbpress-template/

You'll need to connect to your site via FTP and create the templates that way. Unfortunately, there's not an easier way to do so.


Evan

**Comment by ELMANARA** [comment]
I really appreciate your effort and concern, I will check this documentation and hope it will help me with my issue. Please accept my best regards. :)

**Comment by EvanHerman** [comment]
No problem at all. Let us know if you run into any other issues!

Best,
Evan
