### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by px64** [godaddy/wp-primer-theme#147]
For some reason I get this message a lot when using Beaver Builder with Primer theme, but if I switch to a different theme, do the admin action, and then switch back, it works fine.

Fatal error: Cannot access protected property Primer_Customizer_Layouts::$layouts in /data/9/0/160/16/812831/user/834040/htdocs/wordpress1/wp-content/themes/wp-primer-theme-develop/inc/compat/beaver-builder.php on line 30

The two biggest issues are when I try to modify a menu item or launch page builder for the first time.  Once I launch page builder for a page under a different theme, I can then launch BB pagebuilder in Primer from then on.

Any ideas why the protected property cannot be accessed?  I tried uninstalling and reinstalling Beaver Builder and the Primer theme and it didn't help.

**Comment by frankiejarrett** [comment]
@px64 Thanks so much for reporting this! Do you happen to remember what specific actions you were performing in Beaver Builder that triggered the fatal error?

**Comment by px64** [comment]
Yes
1) launching pagebuilder for a new page
2) deleting a menu item

I also use a website that was set up by godaddy that uses primer and beaver
builder (with beaver builder booster) that works fine.  For some reason
this problem is only occurring in my self-installed version, running on a
different host.  Not sure if that matters at all, just trying to help.

**Comment by EvanHerman** [comment]
Hi @px64,

Where are you seeing this error? I'm doing some testing and I'm not running into the fatal error performing the steps you outlined above.

Do you happen to know the differences between the self installed version and the version hosted with GoDaddy? Possibly the PHP versions between the two installs?

I'm looking into this issue today and once I can replicate it on my end I'll be able to come up with a patch to fix things up.

Thanks!

**Comment by px64** [comment]
I upgraded the Primer Theme and Beaver Builder is current, but you bring up a good point on versions of PHP since I am on completely different hosts and am a little suspicious how current the host software (PHP) is on the system that is having the problem.  I will try to get PHP version numbers for both hosts and get back to you.

**Comment by px64** [comment]
The self-installed version is running PHP 5.3.29-p10-gentoo with Primer
1.4.1, Beaver-Builder 1.9.2
The GoDaddy hosted version is running PHP 5.6.27 with Primer 1.4.2 and
Beaver-Builder 1.9.2

**Comment by EvanHerman** [comment]
Hi @px64,

Would you mind updating your self-hosted install to PHP 5.6 or later? As it is, PHP 5.6 is on it's way out and will only receive security updates until December 31st, 2018 (see http://php.net/supported-versions.php).

I believe that may be the issue, but can't be 100% sure. 


Evan

**Comment by px64** [comment]
Evan,

I just located the page that lets me change the version of PHP running on
the host and upgraded to 5.6: problem solved!  Thank you for suggesting it
might be the version of PHP!  It sounded plausible from the moment you
mentioned it, and I wasn't sure if I could simply change versions with the
push of a button, but the option is there on the network solutions
dashboard and it appears to no longer throw an error when I do either of
the operations mentioned above.

**Comment by EvanHerman** [comment]
@px64 Awesome! So glad that I could hop in and help out, and that there wasn't a larger issue at hand.

Have a great rest of your day!


Evan
