### ISSUE TITLE
Dropdown bug

### ISSUE THREAD

**Issue by scottalai** [godaddy/wp-primer-theme#151]
I am using the Stout child theme and I have two dropdown menus. They work fine fullscreen, but if you shrink down the browser window size a little, the second dropdown stays on the screen after you hover over it and won't close automatically like it is supposed to.

**Comment by EvanHerman** [comment]
Hi @scottalai 

I can see the bug on my end, on your site. I will take a look and see if I can replicate it on a test instance that I have setup and see what might be going on.

Evan

**Comment by EvanHerman** [comment]
Hi @scottalai 

I have a fresh WordPress install running the stout theme with a similar navigation to what you have setup, and I'm not running into that issue.

What plugins do you have installed on your site? Maybe I can setup a test instance that closer matches yours.

**Update:**
I am seeing the issue now after shifting things around a bit. I'll try and dig in here and see what's going on.

**Comment by scottalai** [comment]
![plugins](https://cloud.githubusercontent.com/assets/25617039/22710759/8c8bb0ba-ed4c-11e6-90d6-0ddf2c215a6b.jpg)

**Comment by scottalai** [comment]
Do you need the WP login information? Is there code for the dropdown menu
that can be replaced? Perhaps I accidentally changed something in the CSS?

**Comment by frankiejarrett** [comment]
@scottalai No need for credentials, logging in to user installs and performing work is outside the scope of this support channel. We are investigating the issue you described and attempting to reproduce locally. Thanks for reporting it!

**Comment by EvanHerman** [comment]
@scottalai I have been able to reproduce it locally, I am investigating the issue. I can't see anything that would be causing the issue from a quick look through, but I will keep investigating and will update this thread as I discover more information.

**Comment by scottalai** [comment]
I have not heard any news for 6 days now. I really need this glitch fixed. My client is not pleased that the site does not work properly.

**Comment by frankiejarrett** [comment]
Hey @scottalai - Our free themes don't have an SLA, though we do try our best to reproduce and fix reported issues as fast as we can so everyone using them can benefit. If you have business-critical needs we would advise considering a premium paid theme from a WP theme shop that has guaranteed response times.

Some tips on helping make things go faster:

- List the active plugins you are using
- Give us any custom CSS you might be using
- Provide screenshots (when applicable)
- If you are a developer, give us insight into what things you've attempted to solve the problem - in other words, have you done any troubleshooting?

**Comment by scottalai** [comment]
I did list the plugins and provided screenshots. EvanHerman said he was able to reproduce the problem locally.

**Comment by frankiejarrett** [comment]
@scottalai I'm not seeing that information anywhere on this thread... did a separate discussion take place elsewhere?

**Comment by scottalai** [comment]
![bug](https://cloud.githubusercontent.com/assets/25617039/22905219/8a5aecf0-f20d-11e6-9eda-9db4538b1320.jpg)
![plugins](https://cloud.githubusercontent.com/assets/25617039/22905220/8a60145a-f20d-11e6-9c1d-83692c4a7ce3.jpg)

**Comment by frankiejarrett** [comment]
This issue was moved to godaddy/wp-stout-theme#28
