### ISSUE TITLE
How to replace Godaddy footer info with mine? 

### ISSUE THREAD

**Issue by lyonsden10** [godaddy/wp-primer-theme#154]
Can someone please let me know what code to put into the custom css to eliminate the GoDaddy  footer and replace  with my own information?  Thanks,  susan

**Comment by EvanHerman** [comment]
Hi Susan,

It's not possible to easily add your own information, but you can hide the GoDaddy link by using the setting in the customizer. From the dashboard if you go to 'Appearance > Customize' and click on the 'Site Identity' section, you can uncheck the 'Display Author Credit' option.

Example:
![Site Identity Options](https://cldup.com/qtVuipVVo9.png)

**Comment by lyonsden10** [comment]
Thanks. I don't seem to have that option, but I found some code that removed it in the customizer:

.site-info-wrapper .site-info-text { color: #252525; display: none; } 

Thank you again.

**Comment by lyonsden10** [comment]
Thank you for your help.
