### ISSUE TITLE
Switch from Genericons to FA 

### ISSUE THREAD

**Issue by mautematico** [godaddy/wp-primer-theme#163]
Hola,

I just noticed prime is using Genericons for social menu, and using Font Awesome at the same time.
Font Awesome has a wider set of social icons. Why don't jus use FA, if it is already loaded into prime?

**Comment by frankiejarrett** [comment]
Hi @mautematico,

Primer does not use Font Awesome. It's likely being enqueued by a plugin on your site.

We have been discussing in #34 whether or not to switch from Genericons to [Social Logos](https://github.com/Automattic/social-logos) which is much more lightweight than Font Awesome.

**Comment by mautematico** [comment]
My mistake.

I got confused by files like theese:
https://github.com/godaddy/wp-primer-theme/tree/develop/.dev/docs/apigen/godaddy/resources/fonts

But they are under docs/
