### ISSUE TITLE
Introduce FitText to resolve text breakage

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#177]
Continuation of https://github.com/godaddy/wp-stout-theme/pull/34

**Comment by EvanHerman** [comment]
@fjarrett After some testing it looks like there are still some issues using FitText. There was still some issue with `vw` units, unfortunately it wasn't a catch all. Longer words still broke improperly.

As mentioned in the previous thread, using FitText causes a flash of un-styled text in the header - which is slightly noticeable on a local install, so I imagine it's going to more pronounced on a remote server.

Other draw backs:
- The hero looks much different than the initial design (Font size initializes at 72.5px instead of 7rem)
![With Fittext](https://cldup.com/pSjKckjJ43.png)
- Our breakpoints no longer hold, due to the font-size defined inline on the element.

I'm still unsure of the best solution here. Will have to continue testing.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
