### ISSUE TITLE
Ensure compatibility with WooCommerce 3.0.0

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#179]
We should sanity check that Primer runs smoothly on WooCommerce 3.0.0, which will be released April 4th.

Note: The current [release tag is 2.7.0 RC 1](https://github.com/woocommerce/woocommerce/releases/tag/2.7.0-RC1), though the actual release will be dubbed 3.0.0.

cf. https://woocommerce.wordpress.com/2017/03/13/important-update-regarding-the-upcoming-woocommerce-release-2-7-will-be-3-0-0/

**Comment by EvanHerman** [comment]
I went through and tested with the latest WooCommerce RC and all appears to check out. No issues found on my end.
