### ISSUE TITLE
Full width header video customizer toggle

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#183]
As we introduce video headers into Primer and our child themes, we should introduce a new customizer control that allows users to toggle on/off full width video headers.

This would allow users to display the entire video regardless of screen size, instead of stretching the video to fit the width of the header.

**Example**:
![Example](https://cldup.com/NicSXnzJ78.png)

**Comment by anjumukhiya** [comment]
Would be great to have this feature. Also the the video is not responsive at all.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
