### ISSUE TITLE
infinite loading [label:feature request]

### ISSUE THREAD

**Issue by lukapaunovic** [godaddy/wp-primer-theme#190]
As you know it's quite popular today for theme to be able to support infinite loading of posts on scroll.
So I think Primer should choose some of the plugins for that and add support for it in 1.7.0 release
Or even without a plugin in theme itself that would be cool.

**Comment by EvanHerman** [comment]
Hi @lukapaunovic ,

It seems that this may be an edge case, and not a feature that many of our uses would utilize. So introducing such a feature would add a layer of complexity and overhead to the codebase for us to maintain moving forward. 

There are a number of plugins that enable this feature, and using a child theme it wouldn't be that hard to incorporate infinite loading into the child theme.

For now I think it's best that we do not include this feature in the theme, but we can certainly take look at writing a 'How To' article in our [documentation](https://godaddy.github.io/wp-primer-theme/how-to.html) on how this can be achieved within a child theme, or via an mu plugin.


Evan
