### ISSUE TITLE
Header Image Size, menu icon, and Mobile.

### ISSUE THREAD

**Issue by SurfingDude** [godaddy/wp-primer-theme#192]
I'm converting a site from an older WP theme to work better with mobile devices. The header image is a .jpg file and when I resize the Window or try it on a phone the three bars that the main menu collapses into are not aligned correctly and in the smaller screen they push down in the Hero bar and are not usable. This may be related to the image size or to something else. The header image is attached. What can be done to fix this?

![newcert_hdr](https://cloud.githubusercontent.com/assets/15676271/24884051/85f05f0e-1dfc-11e7-9e78-715cd38f3a53.jpg)

**Comment by EvanHerman** [comment]
Hi @SurfingDude,

Can you provide a link to your site as an example? The menu button should stack on top of the header image, and not push anything down.

**Comment by SurfingDude** [comment]
http://test.enccert.org/
is our test site. I'll leave it alone until I see your response. Here is a screenshot that shows the issue.
![screenshot](https://cloud.githubusercontent.com/assets/15676271/24913802/258a18b8-1e87-11e7-8bfd-5540be3ed5aa.png)

**Comment by EvanHerman** [comment]
@SurfingDude Have you tried using a larger image just to test to see if that helps? I Noticed you don't have any hero widget, which may also throw off some of the spacing.

**Comment by SurfingDude** [comment]
The Hero widget seems quite more complex than our needs. All we want is a simple banner with our jpg logo. It should shrink to fit handheld devices and I would expect the primary menu bar to change to something that works on a mobile device.. This image is 1600 x 176 and seems to short for the 3 bars.  Is there a suggested size or aspect ratio for this theme or should I find one by trial-and-error?

I am not displaying the site Title and Tagline. When I do it behaves better but the banner is too big, the Title and Tagline overlay the jpg logo, and the banner hogs the screen of mobile devices.

**Comment by EvanHerman** [comment]
Hi @SurfingDude 

Have you tried using a larger image? The next best thing that I can think of is setting a `min-height` CSS property on the header so it doesn't shrink below a certain image size.

**Comment by SurfingDude** [comment]
Thank for the suggestion. I got past it with a bit of Additional CSS:
.site header {
    height:150px;
}
and an image size of 1200x150. When I shrink it clips left and right leaving the image centered. This seems to work nice on mobile but maybe I need a wider image size in Windows full-screen.
