### ISSUE TITLE
Change the sidebars layout default from Right to Left in a few clicks

### ISSUE THREAD

**Issue by rhavil** [godaddy/wp-primer-theme#193]
I was wondering if it was possible to add a feature that changes the sidebars layout default from Right to Left in a few clicks.
Suppose someone wants to have a right-sided sidebar by default on all the pages.

Thanks a lot for this great theme!
 #enhancement #featurerequest
#20

**Comment by EvanHerman** [comment]
Hi Rhavil,

This is something that we can look into in a future version. I will take a look at the theme and see if it's currently possible via filter, or some other method.

**Comment by frankiejarrett** [comment]
Create a custom must-use plugin and add the following filter:

```php
add_filter( 'primer_default_layout', function () {

	return 'two-column-reversed';

} );
```

More info: https://github.com/godaddy/wp-primer-theme/wiki/Customizing-Primer-with-hooks
