### ISSUE TITLE
How to remove the word post at the top of each post - 

### ISSUE THREAD

**Issue by seoguy** [godaddy/wp-primer-theme#194]
I keep getting the word post at the top of each post - on each article I write and add -
http://www.posttruthfacts.com/concrete-evidence-of-collusion-between-trump-team-and-russia-handed-to-official-investigation/ you can see it here at the top 

Please help if you know what to do 
thanks 

JW

**Comment by EvanHerman** [comment]
Hi @seoguy 

What version of Primer do you have installed? I believe that issue was addressed in a previous release. I will investigate and check to see if I can replicate it on my end as well.

**Comment by seoguy** [comment]
Version: 1.7.0 Thank you for such a fast response Sir

**Comment by EvanHerman** [comment]
Hi @seoguy 

It looks like that occurs when you have your homepage set to 'Your latest posts' on 'Settings > Reading' in the dashboard. If you have a blog posting page, say 'Blog', that lists all of your posts and you click into to read an individual post it will say 'Blog' at the top of the page where yours says 'Posts'.

You can use a filter to alter the page title on the single blog post template. You'll most likely need to setup an [mu-plugin](https://github.com/godaddy/wp-primer-theme/wiki/Customizing-Primer-with-hooks#how-to-create-a-must-use-plugin) with this code in it for things to continue to work after future updates.

The following bit of will allow you to change the titles on your single blog post templates to whatever you choose. Change `Custom Title` with the new string you want to use in its place.

```php
/**
 * Set single blog post template page title.
 *
 * @param  string $title Initial page title, eg: Posts.
 *
 * @return string        Filtered page title.
 */
function primer_blog_page_title( $title ) {

	global $post;

	if ( 'post' !== $post->post_type || ! is_single() ) {

		return $title;

	}

	return esc_html__( 'Custom Title', 'primer' );

}
add_filter( 'primer_the_page_title', 'primer_blog_page_title' );
```
