### ISSUE TITLE
Error on Theme update

### ISSUE THREAD

**Issue by rf-bcit** [godaddy/wp-primer-theme#195]
WordPress site auto updated to 1.7.0 and threw the following error: Fatal error: Call to undefined function has_header_video() in /home/username/public_html/wp-content/themes/primer/functions.php on line 484
Rolled primer theme  back to 1.6.0 and the site came back up.

**Comment by frankiejarrett** [comment]
@rf-bcit Thanks for the report. Video header functionality was introduced in WordPress 4.7 and we added support for that in Primer 1.7.0.

Can you confirm your WordPress version?

**Comment by rf-bcit** [comment]
Just took a look and it is at version 4.6.1 ... just updated it to 4.7.1 now and updated the theme back to 1.7.0 and the site is no longer throwing an error. Thank you for pointing that out.

**Comment by frankiejarrett** [comment]
@EvanHerman This is a valid bug. Primer claims its minimum WP version is 4.4, so it sounds like we're missing a `function_exists( 'has_header_video' )` check somewhere.
