### ISSUE TITLE
Primer Child Theme Uptown Styles Throws Errors

### ISSUE THREAD

**Issue by MMGIFL** [godaddy/wp-primer-theme#196]
Fatal error: Cannot access protected property Primer_Customizer_Layouts::$layouts in /home/content/80/8803880/html/L4p/wp-content/themes/primer/inc/compat/beaver-builder.php on line 34

Is an error i am getting running Primer 1.7.0 (Runs fine on my other site running beaver builder) but the UpTown Style child theme verion 1.1.0 causes the above error

**Comment by frankiejarrett** [comment]
#147 is related

**Comment by MMGIFL** [comment]
upgraded php from 5.3 to 5.4 and it worked

**Comment by frankiejarrett** [comment]
@EvanHerman I suggest we keep this issue open and see if we can fix the root cause anyway. Ideally Primer should work on whatever PHP versions that Beaver Builder supports.

**Comment by EvanHerman** [comment]
@fjarrett Agreed. Backwards compatibility is very important. I will investigate.
