### ISSUE TITLE
Add custom color support w/ color scheme presets

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#2]
- [x] Setup custom colors 

https://github.com/godaddy/wp-primer-theme/blob/feature/customizer/inc/customizer.php#L208-L264
- [x] Add elements where color options are affected (color, background color, border color, etc) 

https://github.com/godaddy/wp-primer-theme/blob/feature/customizer/inc/customizer.php#L422-L458 
- [x] Repeat elements for custom colors outside the color scheme 

https://github.com/godaddy/wp-primer-theme/blob/feature/customizer/inc/customizer.php#L509-L515 

https://github.com/godaddy/wp-primer-theme/blob/feature/customizer/inc/customizer.php#L538-L544 

https://github.com/godaddy/wp-primer-theme/blob/feature/customizer/inc/customizer.php#L538-L544 

https://github.com/godaddy/wp-primer-theme/blob/feature/customizer/inc/customizer.php#L610-L616 

https://github.com/godaddy/wp-primer-theme/blob/feature/customizer/inc/customizer.php#L639-L645

**Comment by tobeycodes** [comment]
@chriswallace I have updated @fjarrett's original issue to reflect changes to make

**Comment by frankiejarrett** [comment]
I handled most of this in the new `Primer_Customizer` class. @jonathanbardo is now working on splitting this up into logical parts so we don't have a 1000 line file.

**Comment by tobeycodes** [comment]
Definitely makes more sense being in a class. Originally it was just pulled out of Twenty Sixteen and was a bit of a mess

**Comment by tobeycodes** [comment]
I know this part was just merged from Twenty Sixteen but it makes no logical sense.

It's a callback for the custom header but changing the site-title and description

https://github.com/godaddy/wp-primer-theme/blob/issue-2-customizer/inc/customizer.php#L90-L115

**Comment by tobeycodes** [comment]
@jonathanbardo by the way sanitize_hex_color isn't loaded outside the customizer

https://github.com/godaddy/wp-primer-theme/blob/issue-2-customizer/inc/customizer/colors.php#L321

**Comment by frankiejarrett** [comment]
@schrapel Thanks I did this, will take a look

**Comment by schrapel** [comment]
Is there anything I can do on this?

**Comment by tobeycodes** [comment]
@fjarrett appreciate your work on this. Can you let me know when this stuff is in a position that we can integrate with the child themes? As of right now we are commenting out the customizer stuff since it fatals on the front end. 

cc @chriswallace for ref

**Comment by frankiejarrett** [comment]
@schrapel Oh really. I'm running 4.6-beta2 and there are no fatals. Looks like `sanitize_hex_color` is being moved outside of the Customizer https://core.trac.wordpress.org/ticket/27583. I will fix this for backwards compat now.

**Comment by tobeycodes** [comment]
That's a good example of something that should have been done 2 years ago when the ticket was opened haha. Thanks

**Comment by frankiejarrett** [comment]
Fixed in https://github.com/godaddy/wp-primer-theme/commit/8712948eb836ca563d912ec15a2ae8566ac645fe
