### ISSUE TITLE
Title tag in H1 tag causes SEO issues

### ISSUE THREAD

**Issue by BRAINPAINBG** [godaddy/wp-primer-theme#202]
The theme is closing the Title tag in H1 tags, which is causing SEO issues. The H1 tag should be used only for the main heading of the visible text and not for the Title tag.  The H1 tag should be present only 1 time per page. Now you have double H1 tags with different content, which is not good for SEO.

**Comment by EvanHerman** [comment]
Hi @BRAINPAINBG,

You are right, and this is something we will investigate to see if there is a reasonable solution.
