### ISSUE TITLE
Menu not working in mobile browsers

### ISSUE THREAD

**Issue by doingandlearning** [godaddy/wp-primer-theme#209]
Hi,

I am having an issue that when my site is viewed in a mobile or narrow browser then, although the responsive menu button appears, it doesn't toggle open a menu when pressed.

The site I'm working on is themotorhomingfamily.com - could someone see if I'm doing something wrong?

Best,
Kevin.

**Comment by EvanHerman** [comment]
Hi @bt2bn 

I just did some testing and I am also encountering a similar issue, but slightly different. The length of the site title is overlapping the mobile menu toggle. However, the menu button on my end still works.

What plugins do you have installed? Can you try disabling your plugins and retesting the menu button?

**Comment by doingandlearning** [comment]
Hi Evan

Thanks for having a look. I've disabled all plugins now and the issue is persisting. 

I then did the classic turn it off and turn it back on again by reinstalling the primer theme. It's working now. 

Thanks for your time. 

Best,
Kevin.

**Comment by EvanHerman** [comment]
Hi @bt2bn 

Great, thanks for keeping us in the loop. Not sure what happened there, maybe a CSS file got tweaked and was not working properly. Glad it is now.

I will have a look into the site title overlapping the mobile menu button to see if we can get a fix out in the next release, which we have slated for release in the next few days.

**Comment by EvanHerman** [comment]
related https://github.com/godaddy/wp-primer-theme/pull/210
