### ISSUE TITLE
Use the latest code from the Hybrid Core framework

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#22]
Primer is currently using parts of [Hybrid Core](https://github.com/justintadlock/hybrid-core) that have since been [deprecated](https://github.com/justintadlock/hybrid-core/blob/master/inc/functions-deprecated.php#L156-L168), namely the **theme layouts** functionality.

These old functions weren't really using a great global namespace either, now everything is prefixed with `hybrid_`.

We should include the necessary functions and new layout objects from the latest release of the Hybrid Core framework in Primer.

**Comment by tobeycodes** [comment]
I'd prefer to use this as little as possible. I think it makes sense to create a layouts.php inside the customizer folder and taking that from Hybrid. Is there anything else we need?

**Comment by frankiejarrett** [comment]
I'm going to rewrite this from scratch. The currently implementation is outdated and can be a lot leaner.

**Comment by frankiejarrett** [comment]
@schrapel This issue would have closed automatically when #26 gets merged.

cf. https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by tobeycodes** [comment]
You're right. I just didn't think it made much sense to keep it open since we won't be using Hybrid for this
