### ISSUE TITLE
inline css

### ISSUE THREAD

**Issue by cefewow** [godaddy/wp-primer-theme#220]
Hi!

<style id='wp-primer-theme-develop-inline-css' type='text/css'>
<style id='wp-primer-theme-develop-fonts-inline-css' type='text/css'>

Is there a way to remove them? Where do they come from?

**Comment by EvanHerman** [comment]
Hi @cefewow,

Those lines are generated by the customizer when using a custom font. If those lines were removed the fonts would not load properly from the Google API, which would cause some issues.

Best,
Evan
