### ISSUE TITLE
Change Base Color Scheme resets 'Display Site Title and Tagline' Setting

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#223]
If you change the base color scheme under appearance->customize->colors if will reset the display site title and tagline Boolean under appearance->customize->site identity to true.

Originally report by @donavynelliott: https://github.com/godaddy/wp-escapade-theme/issues/49

**Comment by latinkreationz** [comment]
Sorry I'm new to this but would this bug be the problem I'm having on my site "www.gothoa.com/contact"?  The page header title is supposed to be white.
