### ISSUE TITLE
Unable to change deafault layout

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#226]
Originally Reported:
https://github.com/godaddy/wp-ascension-theme/issues/73

The default layout template cannot be switched from the 'two-column-default' option anymore. This used to be an option users could set in the customizer, but has been removed with no replacement.

https://github.com/godaddy/wp-primer-theme/blob/develop/inc/customizer/layouts.php#L523-L534

At the moment users can update the default template by updating the `layout` theme mod option.

Example:
`set_theme_mod( 'layout', 'two-column-default' );`

**Comment by frankiejarrett** [comment]
@EvanHerman Does this work?

```php
add_filter( 'primer_default_layout', function () {
	return 'one-column-wide';
} );
```

https://github.com/godaddy/wp-primer-theme/blob/eb85c050499832d0d893af46d7405ac33e55cb10/inc/customizer/layouts.php#L78

**Comment by EvanHerman** [comment]
@fjarrett I thought the same thing, and it does work to filter the default value, but if/and when a user had a version of the theme installed when they could set a default layout in the customizer, a theme_mod option was set which overrides the default value set in that filter - so the filter mentioned above only works for new users who installed the theme _after_ a certain release (v1.4.0 I believe).

https://github.com/godaddy/wp-primer-theme/blob/eb85c050499832d0d893af46d7405ac33e55cb10/inc/customizer/layouts.php#L532

I encountered this issue because I had the theme installed since 1.3.0, and when we removed the customizer options to alter the default layout, my theme_mod option for the default layout stuck around and made it un-filterable.

This should no longer be an issue when we merge #228.

However, maybe we should consider introducing a new filter later in the code execution to allow users to filter the final returned value instead of the default value.

**Comment by frankiejarrett** [comment]
@EvanHerman I see. I'm not particularly fond of that UI as it was confusing to some users and ultimately why it was removed. They would change the "Default Layout" in the Customizer but the live preview would have no effect because it's meant to be "global" setting - this goes against what the Customizer is for, namely showing live previews of changes.

**Comment by EvanHerman** [comment]
@fjarrett Ok. With no additional options page, can you think of an alternative location for it? It would be ideal not to have to instruct users to setup an MU plugin and use a filter just to alter the default layout, and setting up a theme options page seems a bit overkill IMO.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
