### ISSUE TITLE
How do I remove the nav-links at the bottom of Archives pages?

### ISSUE THREAD

**Issue by midami** [godaddy/wp-primer-theme#230]
I would like to remove the nav-links at the bottom of Archives pages (previous and next). How can I do this by inserting custom code into the theme, or (if need be) by editing the archive.php file directly? Thank you!!

**Comment by EvanHerman** [comment]
Hi @midami,

Can you share a link to the page you are referring to? As far as I know, the archive pages have navigation and breadcrumbs, and not just the next/previous links.

What version of Primer do you have installed?

If you want to remove the navigation on the archive page using CSS you can do so using the following (added to the customizers 'Additional CSS' section):

```css
body.archive .navigation.pagination {
   display: none;
}
```

If you wanted to remove it the pagination from the `archive.php` template, you can remove the line `<?php primer_pagination (); ?>` from the template file. [Reference](https://github.com/godaddy/wp-primer-theme/blob/5ecbb2b7a7dd6f577b3cb1ea9e538207a665f2b0/archive.php#L32).

Either way should work to help hide the pagination on the archive page.
