### ISSUE TITLE
Notification for Contact form

### ISSUE THREAD

**Issue by p-ww** [godaddy/wp-primer-theme#232]
Where do I set up the notification email for the Contact Form? Is that somewhere in the WP dashboard of the theme? Thanks.

**Comment by EvanHerman** [comment]
Hi @p-ww,

There is no contact form build into the theme. You may be referring to a third party plugin that you have installed and running alongside the theme - which, if that is the case, there should be a settings page somewhere on your dashboard where you can control the settings for it.

Can you share a link to a page on your site where you have the contact form being display?

Evan

**Comment by p-ww** [comment]
Hi Evan, the page is: http://repatriationglobal.com/contact/

Thanks,
Paul

**Comment by EvanHerman** [comment]
Hi Paul,

It looks like that form is generated using [Ninja Forms](https://wordpress.org/plugins/ninja-forms/).

You should be able to control who the notifications are going to through the Ninja Form settings. Feel free to take a glance at their documentation: https://ninjaforms.com/docs/form-settings/ and https://ninjaforms.com/docs/email/

That should help point you in the right direction .


Evan

**Comment by p-ww** [comment]
Thanks Evan, I'll check that out now!
