### ISSUE TITLE
Some strings can not be translated

### ISSUE THREAD

**Issue by ghost** [godaddy/wp-primer-theme#233]
String containing the symbol _%s_ can not be translated into Russian (and probably other languages).

For example:

`<a class="button" href="<?php the_permalink(); ?>" aria-label="<?php printf( /* translators: post title */ esc_attr__( 'Continue reading %s', 'primer' ), get_the_title() ); ?>"><?php printf( /* translators: right arrow (LTR) / left arrow (RTL) */ esc_html__( 'Continue Reading %s', 'primer' ), is_rtl() ? '&larr;' : '&rarr;' ); ?></a>`

In this example, the strings _Continue reading %s_ cannot be translated. The remaining strings that do not contain symbol %s is translated perfectly.

**Comment by EvanHerman** [comment]
Hi @miniahmet 

What brings you to the conclusion that the string is unable to be translated? It looks like the translations are being pulled into GlotPress just fine: https://translate.wordpress.org/projects/wp-themes/primer/ru/default?page=1

It also looks like the translation exists inside of the .pot translations template: https://github.com/godaddy/wp-primer-theme/blob/98b17266b0800cf33f92db63fb0c474678129b00/languages/primer.pot#L525-L529

**Comment by ghost** [comment]
Hi @EvanHerman 

Yes, the translation exists in _.pot_ files, but the strings that contain the symbol _%s_ not working despite the fact that they are translated. 
![default](https://user-images.githubusercontent.com/28982987/30552450-a5fecf96-9ca6-11e7-8bfa-78aaeebd128d.png)
![default](https://user-images.githubusercontent.com/28982987/30552592-2fd2b9f8-9ca7-11e7-8780-9b5de0f4ac9e.png)

**Comment by EvanHerman** [comment]
Hi @miniahmet 

Let me do some testing and report back here shortly with some findings.

Evan

**Comment by EvanHerman** [comment]
Hi @miniahmet 

I do see the issue on my end as well. I am digging through the code and trying to figure out whats going on. Translations look correct and everything appears to be wrapped properly - so I'm not entirely sure what's going on. It looks to be occurring in other languages as well, so it's not specifically related to Russian.

Let me keep testing and see what I can come up with.

Evan

**Comment by EvanHerman** [comment]
Hi @miniahmet 

Just following up here, it looks like the issue popped up when we released v1.7.0. Versions prior to that work just fine. Digging in further it seems that translation items that are marked 'fuzzy' are what is causing the issue of translations not loading.

I'll need to go through and unmark them as fuzzy and regenerate the `mo` files and things should work again. This will need to get bundled into the next release.

**Comment by EvanHerman** [comment]
@miniahmet I've got a [pull request](https://github.com/godaddy/wp-primer-theme/pull/234) up with the fixes in place on the `language-fix` branch.

Feel free to download the version on the `language-fix` if you'd like these strings updated before the next release. If you run into any issues feel free to drop a comment here or over on the pull request.

https://github.com/godaddy/wp-primer-theme/tree/language-fix

Thanks again for reporting the issue!

Evan

**Comment by ghost** [comment]
Thank You, @EvanHerman!
