### ISSUE TITLE
How to get rid of the title on pages

### ISSUE THREAD

**Issue by wildsafe** [godaddy/wp-primer-theme#235]
On our "home" page, even though the "do not show title" is checked, it still shows up no matter what I try. Please help!!! (www.stopthebleedtraining.org)

**Comment by EvanHerman** [comment]
Hi @wildsafe,

I'm not seeing any title on your homepage. This is what I'm seeing on my end:

![Image](https://cldup.com/dwU066rnom.png)

Is it possible that cache was preventing the change from reflecting on your site? I also did some quick testing on my end and it doesn't look like I'm able to reproduce the bug. Toggling the checkbox for **'Site Identity** > **Display Site Title and Tagline**' from inside of the customizer does seem to alter the visibility of the title in my tests.

<img src="https://cldup.com/V_u5vS_I7r.png" width=250 />


Evan

**Comment by wildsafe** [comment]
I found a plugin that "removes sidebar" and it seems to have worked,
although there's a ton of white space there - just not the title anymore...
