### ISSUE TITLE
Search results page outputting <span> tags around keyword

### ISSUE THREAD

**Issue by davewarfel** [godaddy/wp-primer-theme#236]
I had this problem on my own site, and then found a [thread on stackexchange](https://wordpress.stackexchange.com/questions/277433/search-results-page-outputs-html-code) fixing the issue.

When doing a search, the results page outputs `<span>` and `</span>` tags around the search term.

As pointed out in the stackexchange post, simply removing the `<span>` and `</span>` code from line 49 of inc/helpers.php fixes the issue.

```
$title = sprintf(
	/* translators: search term */
	esc_html__( 'Search Results for: %s', 'primer' ),
	sprintf(
		'<span>%s</span>',
		get_search_query()
	)
);
```
![godaddy-primer-theme-search-results-bug](https://user-images.githubusercontent.com/783021/32410354-9fb62d94-c183-11e7-89b2-c8e68bdd3663.jpg)

**Comment by EvanHerman** [comment]
Hi @davewarfel,

This had been previously reported and will be patched in the upcoming release of Primer.
https://github.com/godaddy/wp-primer-theme/issues/224

**Comment by davewarfel** [comment]
Awesome. Thanks Evan. I'll go ahead and close this issue.
