### ISSUE TITLE
Menu not working on mobile android

### ISSUE THREAD

**Issue by avinash6784** [godaddy/wp-primer-theme#238]
Hi,

I am using primer theme for my blog [(http://devopstechie.com)], when I try to open it from mobile, menu's not working.
Could you please help me to resolve this issue
Very Urgent

**Comment by avinash6784** [comment]
Any update?

**Comment by EvanHerman** [comment]
Hi @avinash6784 ,

It looks like you've switched themes. If you'd like support feel free to switch back to Primer and let us know.

Evan
