### ISSUE TITLE
Comment count includes spurious 'd' character

### ISSUE THREAD

**Issue by JonathanGiles** [godaddy/wp-primer-theme#244]
E.g. http://jonathangiles.net/hello-microsoft/ 

See the '10d Comments' text. I believe this is an issue due to this line of code (refer to the %d towards the end of the line):
https://github.com/godaddy/wp-primer-theme/blob/45a92169c7cc8a6fbee65dba372593b4398f8f7d/templates/parts/loop/post-meta.php#L25

This appears to be a regression introduced by @EvanHerman as part of https://github.com/godaddy/wp-primer-theme/commit/45a92169c7cc8a6fbee65dba372593b4398f8f7d#diff-a4a96713392ea0f2556a30370eccffb8

**Comment by EvanHerman** [comment]
Hi @JonathanGiles 

You are correct - I am seeing that on my end as well. I've got a pull request issued that will get this patched up in the next release. Thanks so much for reporting that here.

I did go through and double check that PR for any other regressions, but the others appear ok.

**Comment by EvanHerman** [comment]
I've got Primer 1.8.2 pushed out to the WordPress.org repository. Feel free to update. If you are still encountering an issue, please us know.
