### ISSUE TITLE
Ascension Header Image quality issue

### ISSUE THREAD

**Issue by stanley1040** [godaddy/wp-primer-theme#247]
I'm using the Ascension theme and my header image quality and brightness is fine downloaded but when inserted as the header image it shows dark and not vivid.  Anyone have an idea what can be the issue?
See attached.  Thanks,
![image capture](https://user-images.githubusercontent.com/36629191/36379371-e6db0b9a-1543-11e8-87a3-08b3e2571f42.PNG)

**Comment by EvanHerman** [comment]
Hi @stanley1040 

This is the design of the theme, and can be adjusted inside of the customizer inside of '**Customizer > Colors > Header**'. You can drop the opacity of the color all the way down to remove the color.

Here is a screenshot to help illustrate what I am referencing - it is the last option in this panel:

![Example](https://cldup.com/pXcGTMBPbK.png)

Let us know if that helps out.

**Comment by stanley1040** [comment]
Thanks Evan…that was it! I appreciate your quick response.

 

Stan Sulkowski

Sideway Enterprise

Direct  773-664-6718

Fax  773-790-4420

 

“Say Hello to More Profits!”

Unique Programs to Grow Your Business

Authorized ISO for CapX Payments – WAVit & Splitit

 <http://getsplitit.com/> GetSplitit.com

 <http://ms.sidwayenterprise.com/> SidewayEnterprise.com

**Comment by EvanHerman** [comment]
No problem at all, glad I could help out. Have a great rest of your day!
