### ISSUE TITLE
Error on woocommerce product page from /inc/compat/woocommerce

### ISSUE THREAD

**Issue by smod10** [godaddy/wp-primer-theme#249]
The error on the shop category page: "Trying to get property of non-object in /home/ds8eb7p0xf3q/public_html/wp-content/themes/primer/inc/compat/woocommerce.php on line 250"

The code on line 250 `$page_id = ( is_shop() ) ? wc_get_page_id( 'shop' ) : $post->ID;`

https://yogaretreatvietnam.com/product-category/june/

Please help look into this issue. Thanks in advance @fjarrett @chriswallace @jonathanbardo @schrapel @wpexplorer @gmays @EvanHerman @lukapaunovic @

**Comment by EvanHerman** [comment]
This should now be resolved in the latest release of Primer (v1.8.3) (Resolved by #250). If for some reason you are still experiencing any issues, feel free to post here and I can investigate a bit further.

https://github.com/godaddy/wp-primer-theme/pull/255
