### ISSUE TITLE
Cache CSS output

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#25]
I think it would make logical sense to cache the entire css output, rather than calculating it on the fly for every page load. 

We can flush the cache when a customizer value changes and set the cache for the first user.

What do you think?

**Comment by frankiejarrett** [comment]
I'm not overly concerned about this since browser cache should handle this pretty well already on subsequent visits, and it would make little difference on our platform since we serve a full page cache from Varnish to logged out users.

**Comment by tobeycodes** [comment]
That's fine. I was under the impression it's going on .org publicly.

**Comment by frankiejarrett** [comment]
It is going on .org, but just saying any platform with a full-page cache and/or object cache makes this a non-issue. Would be interesting to see what the gain would be otherwise. Just store the CSS blob in a theme mod and serve that to logged out users?

**Comment by tobeycodes** [comment]
Let's not worry about this for now. We can come back to it in the future if we need to
