### ISSUE TITLE
Advertising on sides

### ISSUE THREAD

**Issue by BjoernLanwer** [godaddy/wp-primer-theme#252]
Hello,

I’d like to ad advertising to the sides of the main text. They need to be specific to a certain page. I tried using a sidebar. The issue is that now the picture appears on all sides. How can I achieve my goal please ?

Bjoern

**Comment by EvanHerman** [comment]
Hi Bjoern,

Do you have a link to your site to show what you are currently working with? It sounds like you may need to use an HTML widget in the sidebar with a custom element (something like `<div id="ad"></div>`) and then you'll need to use CSS to change the background image of the ad element based on the page you are currently viewing.

Evan

**Comment by BjoernLanwer** [comment]
Thanks for the quick reply! Www.bevdeals.com

——
Bjoern Lanwer

**Comment by EvanHerman** [comment]
This sounds a bit beyond the scope of the support. I would recommend looking around WordPress.org for some plugins to help achieve the task. It also does look like you've switched themes, so you may want to run it by the support team for your current theme.

Have a great day!
