### ISSUE TITLE
reducing page title padding 

### ISSUE THREAD

**Issue by sjaffar111** [godaddy/wp-primer-theme#268]
hi,

I've been trying to reduce the padding around the page title for my page. My theme is Ascension, which is Primer's child theme. I tried everything to no avail.

Please help!

Shehnaz

**Comment by EvanHerman** [comment]
Hi,

You can try and use the following snippet of CSS to tweak the padding around the page title.

```css
.hero .hero-inner {
   padding: 2% 50px;
}
```

You will want to add that to the 'Additional CSS' section of the customizer.

Let us know if that helps!

Evan

**Comment by sjaffar111** [comment]
@EvanHerman hi, it did! thanks a lot!
