### ISSUE TITLE
Changing order of posts

### ISSUE THREAD

**Issue by lilgee34** [godaddy/wp-primer-theme#274]
I have tried everything and I know this shouldn't be so hard. I created a catagory.php page and would like to change the order from post date to alphabetical.

**Comment by EvanHerman** [comment]
Hi @lilgee34 

You can use the filter `pre_get_posts` to alter the order of the query run on the category (archive) page. You'll want to add the following little code snippet into a custom MU plugin that you create.

If you need help creating an MU plugin, we have a tutorial in the theme documentation, which you can find here: https://godaddy.github.io/wp-primer-theme/tutorials-and-examples/tutorials/mu-plugin.html

```php
/**
 * Order the archive page template by post title, ascending
 *
 * @param  object $query Query object.
 */
function reorder_archive_template( $query ) {

	if ( ! is_archive() || ! $query->is_main_query() ) {

		return;

	}

	$query->set( 'orderby', 'title' );
	$query->set( 'order', 'ASC' );

}
add_action( 'pre_get_posts', 'reorder_archive_template' );
```

Once added to the MU plugin you can save the file and view your archive page, which should be sorted in ascending alphabetical order.

Let us know if that helps!

Evan

**Comment by lilgee34** [comment]
Ok - I have tried adding a code like that to the functions.php page. Will that not also work?
g

**Comment by lilgee34** [comment]
I did what you suggested and the plugin is there but now I get this code at the top of every page.

**Comment by lilgee34** [comment]
![screen shot 2018-12-04 at 11 58 09 am](https://user-images.githubusercontent.com/45581863/49532477-cf73bc80-f879-11e8-857e-7036174d7d8e.png)

**Comment by lilgee34** [comment]
![screen shot 2018-12-05 at 10 38 46 am](https://user-images.githubusercontent.com/45581863/49532553-fe8a2e00-f879-11e8-9a85-5a2d508e7308.png)

**Comment by EvanHerman** [comment]
You need to include a `<?php` tag at the top, as outlined in that documentation I've linked to.

**Comment by lilgee34** [comment]
Thank you - I had done that but I guess didn’t upload the right file. 

Everything is working beautifully now.
g

**Comment by EvanHerman** [comment]
Great! I'm glad we could help out and get that resolved. Have a great rest of your week!
