### ISSUE TITLE
Update php version with php 7+

### ISSUE THREAD

**Issue by laurelwebster** [godaddy/wp-primer-theme#278]
Looking to see if the Primer theme and it's child, Lyrical can be updated to support PHP 7+. I don't want to downgrade my php version for security reasons. For reference, this is the error I'm receiving: 

> Fatal error: require_once(): Failed opening required '/www/wp-content/themes/primer/inc/compat/child-themes.php' (include_path='.:/usr/share/php') in /www/wp-content/themes/primer/functions.php on line 89

**Comment by EvanHerman** [comment]
Hi @laurelwebster 

I can take a second look - but I'm not 100% certain that this error is due to PHP 7+ support. We always develop and test on the latest version of PHP, and I haven't encountered this issue before.

I'd be happy to investigate and see if I can replicate the issue on our end.

**Comment by laurelwebster** [comment]
Hi Evan, 

I determined it was an issue with my host’s server, and we got it updated. Thanks for your response though! I really appreciate it.
