### ISSUE TITLE
ISBAT see the editor width change based on the selected page layout

### ISSUE THREAD

**Issue by richtabor** [godaddy/wp-primer-theme#282]
As a user, I should be able to see the proper width of my page as I switch away from the default page layout option. 

**AC:** 
When I select a custom layout, such as the fullwidth layout, the editor should have a class applied to the editor, which can then be used to style the width of the editor properly (using `editor-frame.scss`. 

**Screen recording:**
![ScreenFlow](https://user-images.githubusercontent.com/1813435/57249594-5f798600-7013-11e9-83ab-60ff610902f0.gif)

**Comment by richtabor** [comment]
There is a `layouts.js` file, as well as styling within the `editor-frame.scss` stylesheet, but it does not currently function properly.

**Comment by richtabor** [comment]
Also, the selected layout's class should remain in the admin body classes when saved.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
