### ISSUE TITLE
Specify font weight per font type

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#29]
I think we should be able to pass an array of font weights for each font type. If it's not provided then that font type would default back to 300, 400, 700.

Do you agree?

**Comment by tobeycodes** [comment]
This works although I'm not sure about the logic. I just quickly did it since I need it for a child theme since some use weight of 600.

`get_font()` could potentially in some weird way return null or not pass sanitization but getting the font weight will already have run at that point.

**Comment by frankiejarrett** [comment]
Yeah I almost implemented this but decided against it since I wasn't sure if there was a use case, sounds like there is!

This approach won't really work because weights need to be tied to individual fonts. I'll think of a way to implement this.

**Comment by tobeycodes** [comment]
Well, I thought about doing it to the individual fonts too but it was going to increase the complexity a lot. You'd probably have to do some function like primer_font_weights and you define each weight for each use of the font with a fallback if not defined. That could be a lot to manage... Haha

My solution just assumes the font-weight is defined in the sass and never needs to change. E.g. if you have a medium font weight you have that regardless of what font you use.

**Comment by tobeycodes** [comment]
But I do agree on a individual font basis, would be better

**Comment by frankiejarrett** [comment]
@schrapel Please test this out. This will allow a Child theme to specify weights on a per-font basis.

Rough example:

``` php
add_filter( 'primer_font_weights', function( $weights, $font ) {

    return ( 'Open Sans' === $font ) ? [ 300, 600 ] : $weights;

}, 10, 2 );
```

**Comment by frankiejarrett** [comment]
I just found a flaw in the way fonts are loaded...working on a fix now

**Comment by frankiejarrett** [comment]
@schrapel Alright I think this is getting better now. Fonts were being duplicated when used in multiple types. So if you were using Open Sans for all 3 areas, it would appear 3 times in the Google Font URL call!

Also I decided to pass the `$font_type` to the filter as well. This way a Child theme can decide "I want 700 weight to be available for all Headers" or "Use a 700 weight for Open Sans when used as a Header". And everything will get normalized, and duplicates will be removed, before the final Google Font URL is built. I think this is pretty flexible now.

``` php
add_filter( 'primer_font_weights', function( $weights, $font ) {

    return ( 'Open Sans' === $font ) ? [ 300, 600 ] : $weights;

}, 10, 2 );

add_filter( 'primer_font_weights', function( $weights, $font, $font_type ) {

    return ( 'header_font' === $font_type ) ? [ 400, 600, 700 ] : $weights;

}, 10, 3 );

add_filter( 'primer_font_weights', function( $weights, $font, $font_type ) {

    return ( 'Open Sans' === $font && 'header_font' === $font_type ) ? [ 400, 600, 700 ] : $weights;

}, 10, 3 );
```

**Comment by frankiejarrett** [comment]
Merged into develop in https://github.com/godaddy/wp-primer-theme/commit/ee5cb50a326afb2b9adc20c619a5ee2f5fe4ef48

**Comment by tobeycodes** [comment]
Awesome, but now if you specify a font weight in this way. You also have to specify the css somehow too?

**Comment by frankiejarrett** [comment]
That CSS will just have to be in the child theme and this filter just adds whatever weights the child says it needs. You're right that this doesn't give total control, and maybe we should switch the order of the args in the filter since `$font` will only be used in rare situations - or by folks overriding their child theme.

Can we move forward with what we have now and think about a more complete font weights API after 1.0?

**Comment by tobeycodes** [comment]
Yes definitely. It may even just be easier to have a filter for font
weights globally now and it will just implode them for each font added. But
don't waste time on this for now
