### ISSUE TITLE
Primer theme update to 1.8.7 breaks Blubrry plugin on PHP version 7.x when trying to upload media.  Popup displays WordPress 500 ISE.

### ISSUE THREAD

**Issue by dsnow1985** [godaddy/wp-primer-theme#292]
TROUBLESHOOTING:
Primer version 1.8.6 works perfectly and loads popup window.  When updating theme it breaks this function and displays WordPress 5.2.x new 500 ISE error message.

ERROR_LOG
PHP Fatal error:  Uncaught Error: Call to a member function is_block_editor() on null in /var/www/wp-content/themes/primer/functions.php:409
Stack trace:
#0 /var/www/wp-includes/class-wp-hook.php(284): primer_classic_editor_styles()
#1 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(false, Array)
#2 /var/www/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /var/www/wp-content/plugins/powerpress/powerpressadmin-jquery.php(1060): do_action('admin_print_sty...')
#4 /var/www/wp-content/plugins/powerpress/powerpressadmin-jquery.php(289): powerpress_admin_jquery_header('Select Media', true)
#5 /var/www/wp-content/plugins/powerpress/powerpressadmin.php(96): powerpress_admin_jquery_init()
#6 /var/www/wp-includes/class-wp-hook.php(286): powerpress_admin_init('')
#7 /var/www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#8 /var/www/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#9 /var/www/wp-admin/admin.php(169): do_action('admin_init')
#10 {main}
  thrown in /var/www/wp-content/themes/primer/functions.php on line 409

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
