### ISSUE TITLE
Uninstall button missing

### ISSUE THREAD

**Issue by Bonsai5** [godaddy/wp-primer-theme#293]
I can uninstall all non acitve themes except this one, becasue there's no button for.

Current Version of Wordpress, Primer Theme 1.8.7.

It happens independend of my lanugage setting

**Comment by EvanHerman** [comment]
Hi @Bonsai5 

You'll need to set another theme to active if you want to uninstall Primer. You cannot uninstall an active theme. If the theme is active you won't see any 'Uninstall' button.
