### ISSUE TITLE
Post area 100% height

### ISSUE THREAD

**Issue by lilgee34** [godaddy/wp-primer-theme#295]
I want the post area to fill in even with the right sidebar
![Screen Shot 2019-10-16 at 12 29 38 PM](https://user-images.githubusercontent.com/45581863/66947794-c1053e00-f010-11e9-8c8e-8aa8af1d790d.png)
![Screen Shot 2019-10-16 at 12 30 51 PM](https://user-images.githubusercontent.com/45581863/66947889-e98d3800-f010-11e9-8c00-b61b994a6227.png)

. I have tried everything I can think of.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
