### ISSUE TITLE
WooCommerce theme overrides featured-image header setting

### ISSUE THREAD

**Issue by cgrayson** [godaddy/wp-primer-theme#298]
On sites using this theme and the WooCommerce plugin, posts' featured images are always shown in the header, even if the `use_featured_hero_image` setting is off.

**Comment by nilshellerhoff** [comment]
Can confirm this. The issue comes from here: 
https://github.com/godaddy-wordpress/primer/blob/45156b091c0162584c6e7d5ae9348a5911c3f858/inc/compat/woocommerce.php#L739

Apparently `! is_product() ` is always true when WooCommerce is active

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
