### ISSUE TITLE
Expand/collapse nested nav items on mobile

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#30]
This is a continuation of #12.

As stated by @schrapel in https://github.com/godaddy/wp-primer-theme/issues/12#issuecomment-234714859:

> If we want to introduce clickable dropdowns for children on mobile we will need to add a `<span>` in each element with the arrow since before/after is not part of the DOM.

The current experience is overwhelming when you have a lot of nested nav items:

<img width="467" alt="screen shot 2016-07-24 at 10 20 31 pm" src="https://cloud.githubusercontent.com/assets/522158/17089504/1807c7ec-51ed-11e6-8ce0-d49107a8a4d4.png">

**Comment by jonathanbardo** [comment]
@fjarrett What happens when we want to click the About Us but the interface keeps collapsing the menu after instead of following the link? If we go that way we need to duplicate the link in the sub-menu as well or find another solution.

**Comment by chriswallace** [comment]
This is the best solution, imo: http://www.meanthemes.com/demo/meanmenu/demo.html

**Comment by jonathanbardo** [comment]
@chriswallace I agree. I'll add the markup and I'll let you do the styling.

**Comment by chriswallace** [comment]
Deal.

**Comment by jonathanbardo** [comment]
Done in cecd6fa. I added the + icon in the css that way any child theme could easily override that without any filters.

**Comment by chriswallace** [comment]
Should be all set now. Take a look at c6e425d89c454fcbbf78fc2f64269cc315a5c72f and 4ecab18ebd4381b1fa3fa9312ff65a07ad11dad5 for code/styles related to this. I also implemented this in a child theme to ensure it works well for both.

**Comment by SurfingDude** [comment]
I am not getting the indents on sub and sub-sub menus, has there been some regression? I expect behavior like in the MeanMenu Demo but instead get a flat mobile menu.
I'm using WordPress 4..3 on Godaddy with Primer 1.7.0 installed just this month, and I used the Child Theme Configurator By Lilaea Media to produce a child of Primer (I have yet not modified the Child Theme at all). My test site is:
http://test.enccert.org/
Any help would be appreciated.
