### ISSUE TITLE
On WordPress 5.5 and Gutenberg editor, the background color in editor is no longer inherited(works fine in WP 5.4.2)

### ISSUE THREAD

**Issue by gdandrija** [godaddy/wp-primer-theme#316]
The issue initially submitted on WordPress.org page:

https://wordpress.org/support/topic/wordpress-5-5-page-editor-inherits-font-colour-but-not-background-colour/

It happens only with the 5.5 version of WordPress(tested with Primer theme and plugins off)

Here are the screenshots explaining the issue:

Current appearance(5.5): https://prnt.sc/tybept

Desired Appearance(5.4.2): https://prnt.sc/tybe2z

As seen on the screenshots, while font color is inherited, this is not the case with the background color.

Thanks in advance guys

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
