### ISSUE TITLE
Video in header not showing on mobile - Uptown Style

### ISSUE THREAD

**Issue by gdaleks** [godaddy/wp-primer-theme#317]
Issue reported on WordPress.org: 
https://wordpress.org/support/topic/header-video-is-not-playing-in-mobile-devices/

On user's site: https://prnt.sc/u7n8pz

On my test site: https://prnt.sc/u7n913

Video appears in desktop view: https://prnt.sc/u7n9q4

It seems like the "wp-custom-header" div inside the "hero" div just loses all of it's contents on mobile.

Thanks guys!

**Comment by gdandrija** [comment]
Another user reported the same issue, any progress?

https://wordpress.org/support/topic/video-wont-play-on-mobile-2/

Thanks in advance!

**Comment by pepa95** [comment]
Hello, any new information about this bug?

**Comment by EmirGjerqeku** [comment]
Hello, Did anyone fix this issue, I have the same problem on one of my sites. 
The video is in mp4 format and does not exceed the limit of WordPress file size, it works well for desktop but not for mobile.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
