### ISSUE TITLE
Images and text in Gutenberg have differences in sizing compaired to the default theme.

### ISSUE THREAD

**Issue by gdandrija** [godaddy/wp-primer-theme#318]
Hey guys,

Checking to see if there is something that can be done regarding the image sizing in Gutenberg. User refers to the fact CSS styles applied to page content change the way images appear when the changes are published live.

Initially Submitted on
https://wordpress.org/support/topic/gutenberg-integration-3/#post-13535720

Here is the video showing the issue:
https://drive.google.com/file/d/1KwslYvzg2xVmXqqfVHKg_NdybavaX7QR/view

So the issue refers to differences in image sizing and text appearance entered in Gutenberg, issues have been confirmed by the user.

When the default theme is used, image sizes correspond to the set dimensions better. Seeing if there is a way this can be improved.

Have a nice day,
Andrija

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
