### ISSUE TITLE
Choose whether to display Secondary Sidebar Widget on mobile devices

### ISSUE THREAD

**Issue by PavleMarjanovic** [godaddy/wp-primer-theme#319]
The Secondary Sidebar Widget disappears in mobile view, due to this part of code:

`#tertiary  {
display:none;
}	
}`

The user would like to have the option to choose if the Secondary Sidebar Widget will be displayed in mobile view or not.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
