### ISSUE TITLE
Add support for non-Google fonts

### ISSUE THREAD

**Issue by gdandrija** [godaddy/wp-primer-theme#327]
Is there any way we can add support within the Customizer > Fonts section for other non-Google fonts? Examples:

Arial
Calibri
Helvetica
Verdana
Courier
Georgia
Palatino
Times New Roman

Feature request, initially submitted on WordPress.org
https://wordpress.org/support/topic/how-can-i-add-common-fonts-for-customization/

**Comment by ConsiderThis1** [comment]
Hi, is there any movement on adding Arial to Primer? Using Open Sans slows down my website loading. I've been using DareBoost.com for additional info in addition to that from SiteKit. I've tried, diligently, to add it using Google information, with no luck.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
