### ISSUE TITLE
Should we replace Genericons with Social Logos?

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#34]
Automattic are removing social icons from the latest genericons and separating it out to social logos.

https://github.com/Automattic/social-logos
https://github.com/Automattic/Genericons/pull/98

**Comment by frankiejarrett** [comment]
Oh nice. Hey @jonathanbardo we should consider this for [Contact Widgets](https://github.com/godaddy/wp-contact-widgets) too.

**Comment by jonathanbardo** [comment]
@fjarrett Using this instead of font-awesome?

**Comment by frankiejarrett** [comment]
@jonathanbardo After looking at this a little deeper I now see that we just reference an external stylesheet for FontAwesome, which is pretty lightweight already. For some reason I thought we bundled the font with Contact Widgets.

**Comment by tobeycodes** [comment]
I haven't investigated it but genericons are not working in ie8. social logos that i used on stout are so perhaps we switch sooner than later or adopt font awesome. but maybe it's just a styling issue

**Comment by jonathanbardo** [comment]
@fjarrett Did we officially droped support for ie8?

**Comment by frankiejarrett** [comment]
@jonathanbardo Yes, we've now dropped IE8 support as of https://github.com/godaddy/wp-primer-theme/commit/027e57591b6e54f9181d1b82a775315a59e0419b

**Comment by tobeycodes** [comment]
Cleaning up my open issues. They fixed IE8 support and I can't think of a great reason to switch now.
