### ISSUE TITLE
Videos not working on mobile and also Safari

### ISSUE THREAD

**Issue by ReachExt** [godaddy/wp-primer-theme#348]
We have been banging our heads, but on our website, while there are no issues on laptops but videos are not working on mobile devices.

Examples of such pages are as follows:

[Interview 1](https://www.ejable.com/interviews-with-engineers-in-japan/interview-ruslan-kadyrov-of-rakuten-about-working-in-japan/)

[Interview 2](https://www.ejable.com/inspirations-interviews/a-chat-with-terrie-lloyd/)

**Comment by aledesma-godaddy** [comment]
Hi @ReachExt, It's been some time since you've created this issue but I wanted to let you know what we will be archiving this repository as the theme has now been delisted from WordPress.org. Best regards.
