### ISSUE TITLE
Allow users to create and save their own Color Schemes

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#41]
Currently, users can only pick from a predetermined list of Color Schemes for their theme. A great enhancement would be to allow them to change all the colors in the palette and save it as a custom Color Scheme so they can switch between not only the predetermined schemes, but also their own.

A use-case might be a business that has a custom Color Scheme that matches their brand but they are having a special "Independence Day" promotion and they want to use red, white and blue colors for that week. Currently they would have to write down every color code in their custom Color Scheme in order to switch back easily after the promotion ends.
#42 is related.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
