### ISSUE TITLE
Add styles for Jetpack Featured Content

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#44]
It would be good to have native support for the [Jetpack Featured Content](https://jetpack.com/support/featured-content/) module.

Here is an [example implementation](https://github.com/LiftUX/ascension-theme/blob/4ec66ef90ed4f869fc0af5bb45e572aea5817c74/.dev/sass/partials/_featured-content.scss) from the Ascension theme.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
