### ISSUE TITLE
Default layout is not pre-selected in meta box

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#46]
I noticed that since #33 was merged the Default layout is no longer pre-selected in the meta box. Also there is some spacing issues between the radio buttons.

<img width="292" alt="screen shot 2016-07-30 at 1 38 20 am" src="https://cloud.githubusercontent.com/assets/522158/17268655/7fdbe5c6-55f6-11e6-864a-720ee1564c08.png">

**Comment by jonathanbardo** [comment]
@fjarrett Good catch. Fixed in 4629b2e
