### ISSUE TITLE
Hero area

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#47]
We need to use consistent naming and code for the hero / custom header area. It's definitely my fault for not being consistent. 
1. Decide on a filename / css class to use. hero vs custom header vs site header, etc
2. Ascension uses blockquote, cite, button where as the rest usually just use text + button. We need to make it easy for people to implement this. Should we have a custom widget?

**Comment by tobeycodes** [comment]
This isn't only limited to the hero area it also applies to things like a footer menu. We need to create some consistency across the child themes so we can switch between them easily and maintain all data.

One child theme uses site-info (follows css classes) and another uses footer-menu for the menu. Totally my fault but what do we use and what are the others using

@danielimmke @mrpritchett What have you called your hero and footer menus if applicable? For the hero text widget what html do you use to get the look from the design? 

I assume extra footer widget areas are already consistent since they just numerate (footer-3, footer-4) but will double check these.

**Comment by tobeycodes** [comment]
@fjarrett appreciate your input on this too. naming conventions shouldn't just be left up to me haha

**Comment by frankiejarrett** [comment]
I agree with you. Hero is fine with me.
