### ISSUE TITLE
Page Builder template content area no longer full width.

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-primer-theme#53]
The page builder template's content area should always reach to the edges of the screen, regardless of the layout selected in the Customizer.

**Comment by frankiejarrett** [comment]
@chriswallace @gmays I changed the Page Builder layout in Primer to be full-width but it's not looking quite right to me: http://wpnux.stg-godaddy.com/about/

**Comment by frankiejarrett** [comment]
Never mind on this guys - it was a server configuration issue causing Beaver Builder scripts/styles to not load. We've resolved it.
