### ISSUE TITLE
Contextually-aware inline messages on controls

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#56]
We could help users a lot by spotting known conflicts or contextual issues and displaying an indicator beside the Customizer control that is affected.

For example, if a **Header Image** has been set, then changing the **Header Background Color** control will have no effect in the live preview pane.

A novice user could potentially change this color, wonder why nothing is happening, and only conclude that their site must be broken. To improve this experience we could simply add a special alert icon next to this control, and perhaps a short message to reveal/explain this conflict to the user.

<img width="216" alt="screen shot 2016-08-02 at 6 44 49 pm" src="https://cloud.githubusercontent.com/assets/522158/17349204/88b410cc-58e1-11e6-89a7-ee15beb9d206.png">

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
