### ISSUE TITLE
Nav closes on scroll on mobile

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#57]
During some mobile testing noticed this

**Comment by tobeycodes** [comment]
Additionally if a .menu is position absolute it will open but not close

**Comment by frankiejarrett** [comment]
@schrapel This is because Webkit fires the `window.onresize` event on scroll. We'll probably have to remove or rethink [what we're doing in `navigation.js`](https://github.com/godaddy/wp-primer-theme/blob/e8e4fa99ba9b487b164a391e4c66583fc56d09ce/assets/js/navigation.js#L26).

**Comment by frankiejarrett** [comment]
Fixed in https://github.com/godaddy/wp-primer-theme/commit/7a6a295d370601c18adf26b27fbda8d0c932f8f4
