### ISSUE TITLE
Rename Typography to Fonts?

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#59]
I feel like "Typography" is really just a hip way to say "Fonts" and is less familiar to the majority of users.

<img width="298" alt="screen shot 2016-08-05 at 5 33 13 pm" src="https://cloud.githubusercontent.com/assets/522158/17452214/c5558e54-5b32-11e6-900e-ddbf7608b4cb.png">

**Comment by tobeycodes** [comment]
👍
