### ISSUE TITLE
Add support for Font Type descriptions

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#60]
A potential pain point for users will be having to scan the preview pane to see what is actually changing when switching fonts. The Secondary Font, for example, might only be changing text that happens to be below the fold, which may be out of view.

Additionally, it will be very difficult (maybe even impossible) for the visually impaired to understand the effects of this setting. They will just have to hope it really is being applied to "Primary" and "Secondary" areas.

An easy way to bring more visibility and a better UX to Font Type controls would be to support short descriptions which can be optionally registered by Child Themes using the `primer_font_types` filter.

<img width="287" alt="screen shot 2016-08-05 at 5 38 26 pm" src="https://cloud.githubusercontent.com/assets/522158/17452292/7c4a3bc8-5b33-11e6-8c56-7866b66f8389.png">

**Comment by chriswallace** [comment]
Good call.
