### ISSUE TITLE
Display color schemes as swatches instead of a dropdown

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#62]
Similar to how we now use icons to represent Layouts, I think the same should be done for Color Schemes.  WordPress admin color schemes are displayed this way today in user profiles, actually.

Reading a color scheme name from a list is pretty lame.

<img width="157" alt="screen shot 2016-08-05 at 7 10 55 pm" src="https://cloud.githubusercontent.com/assets/522158/17453344/5c991e4a-5b40-11e6-9353-79536d7dd152.png">

Seeing them in a beautiful swatch stack is pretty awesome.

<img width="298" alt="screen shot 2016-08-05 at 7 08 56 pm" src="https://cloud.githubusercontent.com/assets/522158/17453336/1b9a08d2-5b40-11e6-877f-5e24c4e7e042.png">

Let's be awesome.

Depends on #61.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
