### ISSUE TITLE
Add hero sidebar

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#68]
If Primer registers this sidebar area then child themes wouldn't have to. We will need to propose a design for how this would look in Primer.

**Comment by chriswallace** [comment]
I was thinking about this too. Would make sense considering the amount of work we're doing in child themes for this. I can tackle the design side of this.

**Comment by frankiejarrett** [comment]
@chriswallace Thank you

**Comment by chriswallace** [comment]
@fjarrett Can you take a look at the hero implementation in 4f2ccdf7bdfbd8705558facb63e8aabca0f96487 and let me know if you think this is on the right track?

Add a widget to the hero sidebar and create a title. Then the HTML for a hero widget should be this:

```
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris volutpat ultricies leo, at malesuada eros lacinia eget. Nullam consequat ligula at lectus venenatis suscipit.</p>
<p><a href="#" class="button">Learn More</a></p>
```

**Comment by chriswallace** [comment]
Looks like this as of right now: ![appearance](https://cloud.githubusercontent.com/assets/80830/17639003/38a745c4-60b4-11e6-8950-909c73bd9516.png)
