### ISSUE TITLE
Add color control for hero image overlay

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#71]
It would be awesome if the **Header Background Color** setting could be repurposed to be an overlay when an image is used, instead of being non-applicable when an image is used.

<img width="537" alt="screen shot 2016-08-16 at 10 39 54 pm" src="https://cloud.githubusercontent.com/assets/522158/17723791/601b55f4-6402-11e6-9887-585f560c0f86.png">

We could simply add a new element directly inside `#masthead` called `.color-overlay` and use something like:

``` css
.color-overlay {
    box-shadow: inset 0 0 0 9999em rgba(red, 0.5);
}
```

Bonus: Provide an input range slider to control the overlay color transparency.

<img width="178" alt="screen shot 2016-08-16 at 10 42 12 pm" src="https://cloud.githubusercontent.com/assets/522158/17723823/b4896c2a-6402-11e6-822d-1622bda434df.png">

**Comment by chriswallace** [comment]
![cheering_minions](https://cloud.githubusercontent.com/assets/80830/17939770/b824de60-69f1-11e6-9c1f-33bcdc5f2b8b.gif)
