### ISSUE TITLE
Error gracefully when a color scheme contains undefined colors

### ISSUE THREAD

**Issue by frankiejarrett** [godaddy/wp-primer-theme#73]
Let's say you only have 2 colors defined in the `primer_colors` array of your child theme:

``` php
array(
    'background_color' => array(
        'label'   => 'Background Color',
        'default' => '#fff',
        'css'     => array( ... ),
    ),
    'text_color' => array(
        'label'   => 'Text Color',
        'default' => '#000',
        'css'     => array( ... ),
    ),
);
```

But you have 3 colors defined in a scheme called `sepia` on the `primer_color_schemes` filter:

``` php
array(
    'sepia' => array(
        'label'  => 'Sepia',
        'colors' => array(
            'background_color' => '#efece4',
            'text_color'       => '#eda246',
            'link_color'       => '#e54447',
        ),
    ),
);
```

When you attempt to change the color scheme no swatches will change and it will result in a console error because `link_color` is not defined in `primer_colors`:

```
Uncaught TypeError: api(...) is not a function in color-scheme-control.js?ver=1.0.0:103
```

IMO these errors should be graceful and still allow the colors that _do exist_ to be updated. This will give us the ability to add/remove colors from Primer in the future and maintain partial backwards compatibility with Child Themes without breaking the feature.

**Comment by jonathanbardo** [comment]
@fjarrett Sounds fair, should be a simple fix

**Comment by jonathanbardo** [comment]
@fjarrett Done in b107b01
