### ISSUE TITLE
Add auto-height Javascript for 'expand' mobile drop-downs.

### ISSUE THREAD

**Issue by chriswallace** [godaddy/wp-primer-theme#78]
@fjarrett @jonathanbardo As I go through and fix this issue across multiple themes, I'm realizing there's no great CSS solution for matching the height of the expand button with that of the mobile menu item. When a user changes the font, it will affect the height of the menu items and change the layout. We should use Javascript to set the correct height because otherwise we will end up with mis-matched heights in a variety of cases. Flexbox would work best but is not cross-browser friendly.

Thoughts? Discuss below...

**Comment by jonathanbardo** [comment]
I think flexbox is definitely not something we can use right now so I suggest we come up with a simple JS solution.

**Comment by frankiejarrett** [comment]
@chriswallace @jonathanbardo Would the flexbox styles only be used on mobile? Because my understanding is that it's [almost universally supported](http://caniuse.com/#feat=flexbox) on mobile.

**Comment by ghmicasa** [comment]
Hi, I am using primer theme and the drop down menu doesn't work with mobile version. It has just freezed and no functionality.

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
