### ISSUE TITLE
Fix WooCommerce 'Add to Cart' links overlapping (mobile layout)

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#85]
Related Issue #84 

This is directly related to the 'One Column: Narrow' site layout, on the mobile view.

With WooCommerce active, on the shop page, the 'Add to Cart' links overlap.

![WooCommerce select field overflow](https://cldup.com/Qc5Cs9ufjf.png)

**Comment by frankiejarrett** [comment]
This will be solved by the same fix as #84.
