### ISSUE TITLE
Clean up SCSS / HTML

### ISSUE THREAD

**Issue by tobeycodes** [godaddy/wp-primer-theme#9]
There is a lot of excess code in this parent theme that doesn't make much sense to me.

1) Variables are often repeated and there are way too many to make them useful. E.g. in `_typography` and `_variables`. It's not clear which ones take priority
2) There is a file called `_mixins` but a lot of mixins are not actually in the file
3) The grid system uses a structure like .site-header > .site-header-wrapper > .site-header-inner > .site-header-6 + .site-header-6. There is no need a grid system needs to be nested so much

**Comment by tobeycodes** [comment]
I think it makes more sense if someone else at Lift works on these changes as my knowledge of this framework is limited to only working on the ascension theme but there are a lot of things that have definitely slowed down development

**Comment by frankiejarrett** [comment]
Just a note that our min requirement is IE8

**Comment by tobeycodes** [comment]
@fjarrett Ok. I've removed the suggestion to use flexbox, maybe it's a little early :) 

Susy or Bourbon Neat both will work on IE8 with https://github.com/keithclark/selectivizr

**Comment by tobeycodes** [comment]
@chriswallace I would consider this a priority going forward, since all the other child themes will need to be fixed for the same reasons. It's blocking things like #11 because the typography.scss imports the global mixins that has all the variables repeated which somehow causes a bug for the editor to automatically grow in height with each return.

**Comment by tobeycodes** [comment]
@chriswallace These changes to the scss broke some things. Here's what I've noticed
1. There was a background of #f1f1f1 but now there isn't a default background so it the white area around the content isn't visible since they are both white
2. no background on inputs/textarea
3. no padding on code
4. no padding on blockquote. needs to work both for floated left and right

**Comment by frankiejarrett** [comment]
I'm really not happy with the current SCSS implementation. The more I dig, the deeper into the rabbit hole I go.

**Comment by tobeycodes** [comment]
@fjarrett there aren't really any things I like about it either. It's actually slowed down development a lot because it's written so badly. I'd rather scrap it entirely but it's not a quick fix

**Comment by frankiejarrett** [comment]
It's making me nervous doing all this child theme work on top of this spaghetti parent SCSS....

**Comment by tobeycodes** [comment]
Which is kinda why I gave up using it... My plan was to port this backwards afterwards.

It's very much a WIP, so it's a little messy. But you can litterally build a child theme in a 1/10th of the time if you don't waste time on the parent SCSS crap

https://github.com/LiftUX/stout-theme/tree/master/.dev/sass

**Comment by tobeycodes** [comment]
One thing that gets to me the most is the html structure

.xyz-class > .xyz-wrapper > .xyz-wrapper-inner

There is no need to define a unique wrapper and inner for each block. You just need a single container class that can be used anywhere
