### ISSUE TITLE
Introduce priorities to theme functions

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#91]
The functions hooking into theme actions should include some sort of priority, and should be documented in a doc block above the action it is hooked into. This would help theme developers extend our theme, and know exactly what function is hooked where - and in what order.

Example:
![WooCommerce hook and priority docs](https://cldup.com/XgkFypt4vt.png)

This would also allow theme developers to add additional elements into the theme, in locations that are currently not reachable, such as in-between the navigation and the page header/title.

**Comment by frankiejarrett** [comment]
@EvanHerman Great. I like the reasoning here. Would you agree that these should only be added for action hooks in templates and partials?

**Comment by EvanHerman** [comment]
@fjarrett Yea, I would agree that would be the best location for them. The functions hooking into the templates and partials would benefit from them.

**Comment by EvanHerman** [comment]
This is addressed inside of https://github.com/godaddy/wp-primer-theme/pull/134/commits/3b4dd865542d1db7c65b8ff4108c5a2b676598d1 on the `woocomerce-compat` branch.

**Comment by frankiejarrett** [comment]
Done in #146
