### ISSUE TITLE
Fix the 'Second Sidebar' widget disappearing on shop pages in the customizer

### ISSUE THREAD

**Issue by EvanHerman** [godaddy/wp-primer-theme#92]
Inside of the Customizer, on the WooCommerce 'Shop' pages, the second sidebar area gets hidden. This can be confusing to the user, if they are customizing the theme on the 'Shop' page and want to adjust the second sidebar area.

This happens on any of the themes using 2 sidebars (3 column).

**Comment by frankiejarrett** [comment]
@EvanHerman Oh, looks like this is actually because the Shop page uses a custom `archive-product.php` template provided by WooCommerce, which of course doesn't have `<?php get_sidebar( 'tertiary' ); ?>` in it.
